version: '3.8'

services:
  openwebrx:
    image: openwebrx-hackrf-only:latest
    container_name: openwebrx
    restart: unless-stopped
    ports:
      - "8074:8073"
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - openwebrx-settings:/var/lib/openwebrx
      - openwebrx-config:/etc/openwebrx
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    environment:
      - OPENWEBRX_ADMIN_USER=admin
      - OPENWEBRX_ADMIN_PASSWORD=hackrf
    
volumes:
  openwebrx-settings:
  openwebrx-config:
