version: '3.8'

services:
  openwebrx:
    # Use stable version that properly reads config files
    image: jketterl/openwebrx:1.2.2
    container_name: openwebrx-hackrf
    restart: unless-stopped
    privileged: true
    ports:
      - "8073:8073"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      # Mount configuration directory
      - ./openwebrx-config:/var/lib/openwebrx
    environment:
      - OPENWEBRX_ADMIN_USER=admin
      - OPENWEBRX_ADMIN_PASSWORD=hackrf