version: '3.8'

services:
  openwebrx:
    image: jketterl/openwebrx:latest
    container_name: openwebrx-hackrf
    restart: unless-stopped
    privileged: true
    ports:
      - "8073:8073"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      # Mount our HackRF config directly as the SDR config
      - ./hackrf-only-config.json:/var/lib/openwebrx/sdrs.json:rw
      # Create empty settings and users files so OpenWebRX doesn't create defaults
      - ./openwebrx-settings.json:/var/lib/openwebrx/settings.json:rw
      - ./openwebrx-users.json:/var/lib/openwebrx/users.json:rw
      # Bands configuration
      - ./openwebrx-bands.json:/var/lib/openwebrx/bands.json:rw
      # Bookmarks
      - ./openwebrx-bookmarks.json:/var/lib/openwebrx/bookmarks.json:rw
    environment:
      - OPENWEBRX_ADMIN_USER=admin
      - OPENWEBRX_ADMIN_PASSWORD=hackrf