version: '3.8'

services:
  openwebrx:
    build:
      context: .
      dockerfile: Dockerfile
    image: openwebrx-hackrf:latest
    container_name: openwebrx-hackrf
    restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
    
    # Network ports
    ports:
      - "${OPENWEBRX_PORT:-8073}:8073"
    
    # Volumes for persistence
    volumes:
      # USB devices
      - /dev/bus/usb:/dev/bus/usb:ro
      # Configuration and data persistence
      - openwebrx-settings:/var/lib/openwebrx
      - openwebrx-config:/etc/openwebrx
      # Optional: Mount custom config if you have one
      # - ./openwebrx-hackrf-config.json:/var/lib/openwebrx/sdrs.json
    
    # Device access
    devices:
      # Allow access to all USB devices (adjust if needed)
      - /dev/bus/usb:/dev/bus/usb
    
    # Privileged mode for USB access
    privileged: true
    
    # Environment variables
    environment:
      # Admin credentials
      - OPENWEBRX_ADMIN_USER=${OPENWEBRX_ADMIN_USER:-admin}
      - OPENWEBRX_ADMIN_PASSWORD=${OPENWEBRX_ADMIN_PASSWORD}
      # Optional: Override default settings
      - OPENWEBRX_TITLE=${OPENWEBRX_TITLE:-Stinkster SDR}
      - OPENWEBRX_LOCATION=${OPENWEBRX_LOCATION:-Raspberry Pi}
      # Debug mode (set to true for troubleshooting)
      - OPENWEBRX_DEBUG=${OPENWEBRX_DEBUG:-false}
    
    # Resource limits (optional, adjust based on your Pi)
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Named volumes for data persistence
volumes:
  openwebrx-settings:
    driver: local
  openwebrx-config:
    driver: local

# Optional: Define network if you want to integrate with other services
networks:
  default:
    name: ${DOCKER_COMPOSE_PROJECT_NAME:-stinkster}-net
    driver: bridge